// YKS TERCİH 2026 - LİYAKAT MOTORU KAPSAMLI VE ŞEFFAF VERİ TABANI
const universiteVerileri = [
    // --- 1. FAZ: DOĞRULANMIŞ LOKOMOTİF ÜNİVERSİTELER ---
    { id: 1, isim: "Orta Doğu Teknik Üniversitesi (ODTÜ)", universiteLink: "universiteler/odtu.html", bolum: "Mühendislik & Temel Bilimler", kadro: "%95 Tam Zamanlı", urap: "431", qs: "285", the: "351-400" },
    { id: 2, isim: "Hacettepe Üniversitesi", universiteLink: "universiteler/hacettepe.html", bolum: "Tıp & Sağlık Bilimleri", kadro: "%98 Tam Zamanlı", urap: "524", qs: "751-800", the: "601-800" },
    { id: 3, isim: "Ankara Üniversitesi", universiteLink: "universiteler/ankara-uni.html", bolum: "Hukuk, Tıp & Sosyal Bil.", kadro: "%90 Tam Zamanlı", urap: "782", qs: "801-850", the: "801-1000" },
    { id: 4, isim: "Gazi Üniversitesi", universiteLink: "universiteler/gazi.html", bolum: "Eğitim, Tıp & Mühendislik", kadro: "%89 Tam Zamanlı", urap: "852", qs: "901-950", the: "1001-1200" },
    { id: 5, isim: "Bilkent Üniversitesi", universiteLink: "universiteler/bilkent.html", bolum: "Mühendislik & İktisat", kadro: "%85 Tam Zamanlı", urap: "1235", qs: "502", the: "601-800" },
    { id: 6, isim: "TOBB Ekonomi ve Teknoloji Üni.", universiteLink: "universiteler/tobb.html", bolum: "Mühendislik & İdari Bilimler", kadro: "%80 Tam Zamanlı", urap: "1850", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 7, isim: "İstanbul Teknik Üniversitesi (İTÜ)", universiteLink: "universiteler/itu.html", bolum: "Mühendislik & Mimarlık", kadro: "%92 Tam Zamanlı", urap: "502", qs: "326", the: "501-600" },
    { id: 8, isim: "Boğaziçi Üniversitesi", universiteLink: "universiteler/bogazici.html", bolum: "Temel Bilimler & İdari Bil.", kadro: "%86 Tam Zamanlı", urap: "884", qs: "418", the: "601-800" },
    { id: 9, isim: "Koç Üniversitesi", universiteLink: "universiteler/koc.html", bolum: "Mühendislik & İdari Bilimler", kadro: "%88 Tam Zamanlı", urap: "1032", qs: "401", the: "351-400" },
    { id: 10, isim: "Yıldız Teknik Üniversitesi (YTÜ)", universiteLink: "universiteler/ytu.html", bolum: "Mühendislik & Mimarlık", kadro: "%87 Tam Zamanlı", urap: "931", qs: "851-900", the: "1001-1200" },
    { id: 11, isim: "İstanbul Üniversitesi", universiteLink: "universiteler/istanbul.html", bolum: "Tıp, Hukuk & Edebiyat", kadro: "%94 Tam Zamanlı", urap: "650", qs: "701-750", the: "801-1000" },
    { id: 12, isim: "Marmara Üniversitesi", universiteLink: "universiteler/marmara.html", bolum: "İktisat, İlahiyat & İletişim", kadro: "%85 Tam Zamanlı", urap: "1050", qs: "1001-1200", the: "1201-1500" },
    { id: 13, isim: "Sabancı Üniversitesi", universiteLink: "universiteler/sabanci.html", bolum: "Mühendislik & Yönetim", kadro: "%82 Tam Zamanlı", urap: "1350", qs: "501-550", the: "401-500" },
    { id: 14, isim: "Ege Üniversitesi", universiteLink: "universiteler/ege.html", bolum: "Tıp, Ziraat & Fen", kadro: "%91 Tam Zamanlı", urap: "950", qs: "1001-1200", the: "1001-1200" },
    { id: 15, isim: "Dokuz Eylül Üniversitesi", universiteLink: "universiteler/deu.html", bolum: "Tıp, Mühendislik & Hukuk", kadro: "%88 Tam Zamanlı", urap: "1150", qs: "1201-1400", the: "1201-1500" },
    { id: 16, isim: "İzmir Yüksek Teknoloji Enstitüsü (İYTE)", universiteLink: "universiteler/iyte.html", bolum: "Mimarlık & İleri Teknoloji", kadro: "%84 Tam Zamanlı", urap: "1450", qs: "1201-1400", the: "Listelenmiyor" },

    // --- 2. FAZ: DOĞRULANMIŞ ANADOLU ÜNİVERSİTELERİ ---
    { id: 17, isim: "Erciyes Üniversitesi (Kayseri)", universiteLink: "universiteler/erciyes.html", bolum: "Tıp & Mühendislik", kadro: "%86 Tam Zamanlı", urap: "1100", qs: "1201-1400", the: "1001-1200" },
    { id: 18, isim: "Karadeniz Teknik Üniversitesi (Trabzon)", universiteLink: "universiteler/ktu.html", bolum: "Mühendislik & Orman", kadro: "%87 Tam Zamanlı", urap: "1300", qs: "Listelenmiyor", the: "1501+" },
    { id: 19, isim: "Çukurova Üniversitesi (Adana)", universiteLink: "universiteler/cukurova.html", bolum: "Ziraat, Tıp & Mühendislik", kadro: "%88 Tam Zamanlı", urap: "1250", qs: "1201-1400", the: "1201-1500" },
    { id: 20, isim: "Akdeniz Üniversitesi (Antalya)", universiteLink: "universiteler/akdeniz.html", bolum: "Tıp & Turizm", kadro: "%85 Tam Zamanlı", urap: "1200", qs: "1201-1400", the: "1501+" },
    { id: 21, isim: "Anadolu Üniversitesi (Eskişehir)", universiteLink: "universiteler/anadolu.html", bolum: "İletişim, Havacılık & AÖF", kadro: "%80 Tam Zamanlı", urap: "1600", qs: "1201-1400", the: "1201-1500" },
    { id: 22, isim: "Atatürk Üniversitesi (Erzurum)", universiteLink: "universiteler/ataturk.html", bolum: "Genel Kapsamlı (Tıp/Ziraat)", kadro: "%90 Tam Zamanlı", urap: "1350", qs: "Listelenmiyor", the: "1501+" },
    { id: 23, isim: "Ondokuz Mayıs Üniversitesi (Samsun)", universiteLink: "universiteler/omu.html", bolum: "Tıp, Eğitim & Ziraat", kadro: "%86 Tam Zamanlı", urap: "1400", qs: "1401+", the: "1501+" },
    { id: 24, isim: "Gebze Teknik Üniversitesi (Kocaeli)", universiteLink: "universiteler/gtu.html", bolum: "İleri Mühendislik & Temel Bil.", kadro: "%82 Tam Zamanlı", urap: "1500", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 25, isim: "Çanakkale Onsekiz Mart Üniversitesi", universiteLink: "universiteler/comu.html", bolum: "Arkeoloji, Tarih & Ziraat", kadro: "%84 Tam Zamanlı", urap: "1652", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 26, isim: "Bursa Uludağ Üniversitesi", universiteLink: "universiteler/uludag.html", bolum: "Tıp, Otomotiv & İktisat", kadro: "%86 Tam Zamanlı", urap: "1450", qs: "Listelenmiyor", the: "1501+" },
    { id: 27, isim: "Sakarya Üniversitesi", universiteLink: "universiteler/sakarya.html", bolum: "Mühendislik & İdari Bilimler", kadro: "%83 Tam Zamanlı", urap: "1520", qs: "1201-1400", the: "1501+" },
    { id: 28, isim: "Kocaeli Üniversitesi", universiteLink: "universiteler/kocaeli.html", bolum: "Mühendislik & Tıp", kadro: "%84 Tam Zamanlı", urap: "1580", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 29, isim: "Süleyman Demirel Üniversitesi (Isparta)", universiteLink: "universiteler/sdu.html", bolum: "Tıp & Diş Hekimliği", kadro: "%85 Tam Zamanlı", urap: "1650", qs: "Listelenmiyor", the: "1501+" },
    { id: 30, isim: "Selçuk Üniversitesi (Konya)", universiteLink: "universiteler/selcuk.html", bolum: "Veterinerlik, Hukuk & Diş", kadro: "%87 Tam Zamanlı", urap: "1380", qs: "Listelenmiyor", the: "1501+" },
    { id: 31, isim: "Gaziantep Üniversitesi", universiteLink: "universiteler/gaziantep.html", bolum: "Mühendislik & Tıp", kadro: "%82 Tam Zamanlı", urap: "1720", qs: "Listelenmiyor", the: "1501+" },
    { id: 32, isim: "Dicle Üniversitesi (Diyarbakır)", universiteLink: "universiteler/dicle.html", bolum: "Tıp & Ziraat", kadro: "%81 Tam Zamanlı", urap: "1850", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 33, isim: "Fırat Üniversitesi (Elazığ)", universiteLink: "universiteler/firat.html", bolum: "Mühendislik & Teknoloji", kadro: "%88 Tam Zamanlı", urap: "1280", qs: "Listelenmiyor", the: "1201-1500" },
    { id: 34, isim: "İnönü Üniversitesi (Malatya)", universiteLink: "universiteler/inonu.html", bolum: "Tıp (Karaciğer Nakli Enstitüsü)", kadro: "%85 Tam Zamanlı", urap: "1480", qs: "Listelenmiyor", the: "Listelenmiyor" },

    // --- 3. FAZ: DOĞRULANMIŞ BÜYÜK VAKIF ÜNİVERSİTELERİ ---
    { id: 35, isim: "Başkent Üniversitesi (Ankara)", universiteLink: "universiteler/baskent.html", bolum: "Tıp, Diş & Hukuk", kadro: "%80 Tam Zamanlı", urap: "1920", qs: "Listelenmiyor", the: "1501+" },
    { id: 36, isim: "Çankaya Üniversitesi (Ankara)", universiteLink: "universiteler/cankaya.html", bolum: "Mühendislik & Hukuk", kadro: "%75 Tam Zamanlı", urap: "1850", qs: "Listelenmiyor", the: "401-500" },
    { id: 37, isim: "Yeditepe Üniversitesi (İstanbul)", universiteLink: "universiteler/yeditepe.html", bolum: "Tıp, Diş & Eczacılık", kadro: "%78 Tam Zamanlı", urap: "1980", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 38, isim: "Bahçeşehir Üniversitesi (BAU)", universiteLink: "universiteler/bau.html", bolum: "İletişim, Hukuk & Mühendislik", kadro: "%72 Tam Zamanlı", urap: "1950", qs: "Listelenmiyor", the: "1201-1500" },
    { id: 39, isim: "Özyeğin Üniversitesi (İstanbul)", universiteLink: "universiteler/ozyegin.html", bolum: "İşletme, Hukuk & Mimarlık", kadro: "%85 Tam Zamanlı", urap: "2100", qs: "Listelenmiyor", the: "801-1000" },
    { id: 40, isim: "Medipol Üniversitesi (İstanbul)", universiteLink: "universiteler/medipol.html", bolum: "Tıp, Diş & Sağlık Bilimleri", kadro: "%70 Tam Zamanlı", urap: "2200", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 41, isim: "Acıbadem Üniversitesi (İstanbul)", universiteLink: "universiteler/acibadem.html", bolum: "Tıp & Sağlık Bilimleri", kadro: "%82 Tam Zamanlı", urap: "2050", qs: "Listelenmiyor", the: "1501+" },
    { id: 42, isim: "Bezmiâlem Vakıf Üniversitesi", universiteLink: "universiteler/bezmialem.html", bolum: "Tıp, Diş Hekimliği & Eczacılık", kadro: "%88 Tam Zamanlı", urap: "1890", qs: "Listelenmiyor", the: "1501+" },
    { id: 43, isim: "Kadir Has Üniversitesi (İstanbul)", universiteLink: "universiteler/kadirhas.html", bolum: "İletişim, Sanat & Hukuk", kadro: "%75 Tam Zamanlı", urap: "2400", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 44, isim: "Yaşar Üniversitesi (İzmir)", universiteLink: "universiteler/yasar.html", bolum: "Sanat, Tasarım & İletişim", kadro: "%70 Tam Zamanlı", urap: "2500", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 45, isim: "İzmir Ekonomi Üniversitesi", universiteLink: "universiteler/izmirekonomi.html", bolum: "İktisat & Lojistik", kadro: "%72 Tam Zamanlı", urap: "2350", qs: "Listelenmiyor", the: "Listelenmiyor" },

    // --- 4. FAZ: YENİ EKLENEN PRESTİJLİ VE TEMATİK DEVLET ÜNİVERSİTELERİ ---
    { id: 46, isim: "Galatasaray Üniversitesi (İstanbul)", universiteLink: "universiteler/gsu.html", bolum: "Hukuk, İktisat & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 47, isim: "Türk-Alman Üniversitesi (İstanbul)", universiteLink: "universiteler/tau.html", bolum: "Mühendislik & Hukuk", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 48, isim: "Mimar Sinan Güzel Sanatlar Üniversitesi (İstanbul)", universiteLink: "universiteler/msgsu.html", bolum: "Mimarlık & Güzel Sanatlar", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 49, isim: "Sağlık Bilimleri Üniversitesi (İstanbul/Ankara)", universiteLink: "universiteler/sbu.html", bolum: "Tıp, Diş Hekimliği & Sağlık Bil.", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 50, isim: "Abdullah Gül Üniversitesi (Kayseri)", universiteLink: "universiteler/agu.html", bolum: "Mühendislik & Yaşam Bilimleri", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "601-800" },
    { id: 51, isim: "Türk-Japon Bilim ve Teknoloji Üniversitesi (İstanbul)", universiteLink: "universiteler/tju.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 52, isim: "Ankara Müzik ve Güzel Sanatlar Üniversitesi", universiteLink: "universiteler/amgsu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 53, isim: "Necmettin Erbakan Üniversitesi (Konya)", universiteLink: "universiteler/neu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },

    // --- 5. FAZ: DİĞER DEVLET ÜNİVERSİTELERİ (ŞEFFAF - BİLGİ YOK) ---
    { id: 54, isim: "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi", universiteLink: "universiteler/atu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 55, isim: "Adıyaman Üniversitesi", universiteLink: "universiteler/adiyaman.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 56, isim: "Afyon Kocatepe Üniversitesi", universiteLink: "universiteler/aku.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 57, isim: "Afyonkarahisar Sağlık Bilimleri Üniversitesi", universiteLink: "universiteler/afsu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 58, isim: "Ağrı İbrahim Çeçen Üniversitesi", universiteLink: "universiteler/agri.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 59, isim: "Aksaray Üniversitesi", universiteLink: "universiteler/aksaray.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 60, isim: "Alanya Alaaddin Keykubat Üniversitesi", universiteLink: "universiteler/alanya.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 61, isim: "Amasya Üniversitesi", universiteLink: "universiteler/amasya.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 62, isim: "Ankara Hacı Bayram Veli Üniversitesi", universiteLink: "universiteler/ahbv.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 63, isim: "Ankara Sosyal Bilimler Üniversitesi", universiteLink: "universiteler/asbu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 64, isim: "Ankara Yıldırım Beyazıt Üniversitesi", universiteLink: "universiteler/aybu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 65, isim: "Ardahan Üniversitesi", universiteLink: "universiteler/ardahan.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 66, isim: "Artvin Çoruh Üniversitesi", universiteLink: "universiteler/artvin.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 67, isim: "Aydın Adnan Menderes Üniversitesi", universiteLink: "universiteler/adu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 68, isim: "Balıkesir Üniversitesi", universiteLink: "universiteler/balikesir.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 69, isim: "Bandırma Onyedi Eylül Üniversitesi", universiteLink: "universiteler/bandirma.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 70, isim: "Break Üniversitesi / Bartın Üniversitesi", universiteLink: "universiteler/bartin.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 71, isim: "Batman Üniversitesi", universiteLink: "universiteler/batman.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 72, isim: "Bayburt Üniversitesi", universiteLink: "universiteler/bayburt.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 73, isim: "Bilecik Şeyh Edebali Üniversitesi", universiteLink: "universiteler/bilecik.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 74, isim: "Bingöl Üniversitesi", universiteLink: "universiteler/bingol.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 75, isim: "Bitlis Eren Üniversitesi", universiteLink: "universiteler/bitlis.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 76, isim: "Bolu Abant İzzet Baysal Üniversitesi", universiteLink: "universiteler/ibu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 77, isim: "Burdur Mehmet Akif Ersoy Üniversitesi", universiteLink: "universiteler/maku.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 78, isim: "Bursa Teknik Üniversitesi", universiteLink: "universiteler/btu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 79, isim: "Çankırı Karatekin Üniversitesi", universiteLink: "universiteler/karatekin.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 80, isim: "Çorum Hitit Üniversitesi", universiteLink: "universiteler/hitit.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 81, isim: "Düzce Üniversitesi", universiteLink: "universiteler/duzce.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 82, isim: "Edirne Trakya Üniversitesi", universiteLink: "universiteler/trakya.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 83, isim: "Erzincan Binali Yıldırım Üniversitesi", universiteLink: "universiteler/erzincan.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 84, isim: "Erzurum Teknik Üniversitesi", universiteLink: "universiteler/erzurumteknik.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 85, isim: "Eskişehir Osmangazi Üniversitesi", universiteLink: "universiteler/ogu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 86, isim: "Eskişehir Teknik Üniversitesi", universiteLink: "universiteler/estu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 87, isim: "Gaziantep İslam Bilim ve Teknoloji Üniversitesi", universiteLink: "universiteler/gibtu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 88, isim: "Giresun Üniversitesi", universiteLink: "universiteler/giresun.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 89, isim: "Gümüşhane Üniversitesi", universiteLink: "universiteler/gumushane.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 90, isim: "Hakkari Üniversitesi", universiteLink: "universiteler/hakkari.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 91, isim: "Hatay Mustafa Kemal Üniversitesi", universiteLink: "universiteler/mku.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 102, isim: "Kahramanmaraş İstiklal Üniversitesi", universiteLink: "universiteler/istiklal.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 103, isim: "Tarsus Üniversitesi", universiteLink: "universiteler/tarsus.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 104, isim: "Iğdır Üniversitesi", universiteLink: "universiteler/igdir.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 105, isim: "Isparta Uygulamalı Bilimler Üniversitesi", universiteLink: "universiteler/isubu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 106, isim: "İskenderun Teknik Üniversitesi (İSTE)", universiteLink: "universiteler/iste.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 107, isim: "İstanbul Cerrahpaşa Üniversitesi", universiteLink: "universiteler/cerrahpasa.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 108, isim: "İstanbul Medeniyet Üniversitesi", universiteLink: "universiteler/medeniyet.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 109, isim: "İzmir Bakırçay Üniversitesi", universiteLink: "universiteler/bakircay.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 110, isim: "İzmir Demokrasi Üniversitesi", universiteLink: "universiteler/demokrasi.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 111, isim: "İzmir Katip Çelebi Üniversitesi", universiteLink: "universiteler/ikcu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 112, isim: "Kahramanmaraş Sütçü İmam Üniversitesi", universiteLink: "universiteler/ksu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 113, isim: "Karabük Üniversitesi", universiteLink: "universiteler/karabuk.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 114, isim: "Karamananoğlu Mehmetbey Üniversitesi", universiteLink: "universiteler/kmu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 115, isim: "Kars Kafkas Üniversitesi", universiteLink: "universiteler/kafkas.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 116, isim: "Kastamonu Üniversitesi", universiteLink: "universiteler/kastamonu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 117, isim: "Kırıkkale Üniversitesi", universiteLink: "universiteler/kirikkale.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 118, isim: "Kırklareli Üniversitesi", universiteLink: "universiteler/kirklareli.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 119, isim: "Kırşehir Ahi Evran Üniversitesi", universiteLink: "universiteler/ahievran.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 120, isim: "Kilis 7 Aralık Üniversitesi", universiteLink: "universiteler/kilis.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 121, isim: "Konya Teknik Üniversitesi", universiteLink: "universiteler/ktun.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 122, isim: "Kütahya Dumlupınar Üniversitesi", universiteLink: "universiteler/dpu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 123, isim: "Kütahya Sağlık Bilimleri Üniversitesi", universiteLink: "universiteler/ksbu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 124, isim: "Malatya Turgut Özal Üniversitesi", universiteLink: "universiteler/mto.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 125, isim: "Manisa Celal Bayar Üniversitesi", universiteLink: "universiteler/cbu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 126, isim: "Mardin Artuklu Üniversitesi", universiteLink: "universiteler/artuklu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 127, isim: "Mersin Üniversitesi", universiteLink: "universiteler/mersin.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 128, isim: "Muğla Sıtkı Koçman Üniversitesi", universiteLink: "universiteler/mu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 129, isim: "Muş Alparslan Üniversitesi", universiteLink: "universiteler/mus.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 130, isim: "Nevşehir Hacı Bektaş Veli Üniversitesi", universiteLink: "universiteler/nevsehir.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 131, isim: "Niğde Ömer Halisdemir Üniversitesi", universiteLink: "universiteler/ohu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 132, isim: "Ordu Üniversitesi", universiteLink: "universiteler/ordu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 133, isim: "Osmaniye Korkut Ata Üniversitesi", universiteLink: "universiteler/osmaniye.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 134, isim: "Pamukkale Üniversitesi (Denizli)", universiteLink: "universiteler/pau.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 135, isim: "Rize Recep Tayyip Erdoğan Üniversitesi", universiteLink: "universiteler/erdogan.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 136, isim: "Sakarya Uygulamalı Bilimler Üniversitesi", universiteLink: "universiteler/subu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 137, isim: "Samsun Üniversitesi", universiteLink: "universiteler/samsun.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 138, isim: "Siirt Üniversitesi", universiteLink: "universiteler/siirt.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 139, isim: "Sinop Üniversitesi", universiteLink: "universiteler/sinop.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 140, isim: "Sivas Cumhuriyet Üniversitesi", universiteLink: "universiteler/cumhuriyet.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 141, isim: "Sivas Bilim ve Teknoloji Üniversitesi", universiteLink: "universiteler/sbtu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 142, isim: "Şanlıurfa Harran Üniversitesi", universiteLink: "universiteler/harran.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 143, isim: "Şırnak Üniversitesi", universiteLink: "universiteler/sirnak.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 144, isim: "Tekirdağ Namık Kemal Üniversitesi", universiteLink: "universiteler/nku.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 145, isim: "Tokat Gaziosmanpaşa Üniversitesi", universiteLink: "universiteler/gop.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 146, isim: "Trabzon Üniversitesi", universiteLink: "universiteler/trabzon.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 147, isim: "Tunceli Munzur Üniversitesi", universiteLink: "universiteler/munzur.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 148, isim: "Uşak Üniversitesi", universiteLink: "universiteler/usak.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 149, isim: "Van Yüzüncü Yıl Üniversitesi", universiteLink: "universiteler/yyu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 150, isim: "Yalova Üniversitesi", universiteLink: "universiteler/yalova.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 151, isim: "Yozgat Bozok Üniversitesi", universiteLink: "universiteler/bozok.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 152, isim: "Zonguldak Bülent Ecevit Üniversitesi", universiteLink: "universiteler/beun.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },

    // --- 6. FAZ: VERİSİ HENÜZ İNCELENEN VAKIF ÜNİVERSİTELERİ (ŞEFFAF - BİLGİ YOK) ---
    { id: 153, isim: "Ankara Medipol Üniversitesi", universiteLink: "universiteler/ankaramedipol.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 154, isim: "Antalya Bilim Üniversitesi", universiteLink: "universiteler/antalyabilim.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 155, isim: "Atılım Üniversitesi (Ankara)", universiteLink: "universiteler/atilim.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 156, isim: "Avrasya Üniversitesi (Trabzon)", universiteLink: "universiteler/avrasya.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 157, isim: "Beykent Üniversitesi (İstanbul)", universiteLink: "universiteler/beykent.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 158, isim: "Beykoz Üniversitesi (İstanbul)", universiteLink: "universiteler/beykoz.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 159, isim: "Biruni Üniversitesi (İstanbul)", universiteLink: "universiteler/biruni.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 160, isim: "Çağ Üniversitesi (Mersin)", universiteLink: "universiteler/cag.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 161, isim: "Doğuş Üniversitesi (İstanbul)", universiteLink: "universiteler/dogus.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 162, isim: "Fatih Sultan Mehmet Vakıf Üni.", universiteLink: "universiteler/fsm.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 163, isim: "Fenerbahçe Üniversitesi", universiteLink: "universiteler/fbu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 164, isim: "Haliç Üniversitesi", universiteLink: "universiteler/halic.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 165, isim: "Hasan Kalyoncu Üniversitesi (Gaziantep)", universiteLink: "universiteler/hku.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 166, isim: "Işık Üniversitesi (İstanbul)", universiteLink: "universiteler/isik.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 167, isim: "İbn Haldun Üniversitesi", universiteLink: "universiteler/ihu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 168, isim: "İstanbul Arel Üniversitesi", universiteLink: "universiteler/arel.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 169, isim: "İstanbul Atlas Üniversitesi", universiteLink: "universiteler/atlas.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 170, isim: "İstanbul Aydın Üniversitesi", universiteLink: "universiteler/aydin.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 171, isim: "İstanbul Bilgi Üniversitesi", universiteLink: "universiteler/bilgi.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 172, isim: "İstanbul Galata Üniversitesi", universiteLink: "universiteler/galata.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 173, isim: "İstanbul Gelişim Üniversitesi", universiteLink: "universiteler/gelisim.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 174, isim: "İstanbul Kent Üniversitesi", universiteLink: "universiteler/kent.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 175, isim: "İstanbul Kültür Üniversitesi", universiteLink: "universiteler/kultur.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 176, isim: "İstanbul Okan Üniversitesi", universiteLink: "universiteler/okan.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 177, isim: "İstanbul Rumeli Üniversitesi", universiteLink: "universiteler/rumeli.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 178, isim: "İstanbul Sabahattin Zaim Üniversitesi", universiteLink: "universiteler/izu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 179, isim: "İstanbul Sağlık ve Teknoloji Üniversitesi", universiteLink: "universiteler/istun.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 180, isim: "İstanbul Ticaret Üniversitesi", universiteLink: "universiteler/ticaret.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 181, isim: "İstinye Üniversitesi (İstanbul)", universiteLink: "universiteler/istinye.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 182, isim: "Kapadokya Üniversitesi (Nevşehir)", universiteLink: "universiteler/kapadokya.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 183, isim: "Karatay Üniversitesi (Konya)", universiteLink: "universiteler/karatay.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 184, isim: "Kocaeli Sağlık ve Teknoloji Üniversitesi", universiteLink: "universiteler/kostu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 185, isim: "Lokman Hekim Üniversitesi (Ankara)", universiteLink: "universiteler/lokmanhekim.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 186, isim: "Maltepe Üniversitesi (İstanbul)", universiteLink: "universiteler/maltepe.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 187, isim: "MEF Üniversitesi (İstanbul)", universiteLink: "universiteler/mef.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 188, isim: "Nişantaşı Üniversitesi (İstanbul)", universiteLink: "universiteler/nisantasi.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 189, isim: "Nuh Naci Yazgan Üniversitesi (Kayseri)", universiteLink: "universiteler/nny.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 190, isim: "Ostim Teknik Üniversitesi (Ankara)", universiteLink: "universiteler/ostim.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 191, isim: "Piri Reis Üniversitesi (İstanbul)", universiteLink: "universiteler/pirireis.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 192, isim: "Sanko Üniversitesi (Gaziantep)", universiteLink: "universiteler/sanko.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 193, isim: "TED Üniversitesi (Ankara)", universiteLink: "universiteler/tedu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 194, isim: "Toros Üniversitesi (Mersin)", universiteLink: "universiteler/toros.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 195, isim: "Ufuk Üniversitesi (Ankara)", universiteLink: "universiteler/ufuk.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 196, isim: "Üsküdar Üniversitesi (İstanbul)", universiteLink: "universiteler/uskudar.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 197, isim: "Yaşar Üniversitesi (İzmir)", universiteLink: "universiteler/yasar.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 198, isim: "Yüksek İhtisas Üniversitesi (Ankara)", universiteLink: "universiteler/yiu.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 199, isim: "Ankara Bilim Üniversitesi", universiteLink: "universiteler/ankarabilim.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 200, isim: "Mudanya Üniversitesi (Bursa)", universiteLink: "universiteler/mudanya.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" }
];
