// YKS TERCİH 2026 - LİYAKAT MOTORU ŞEFFAF VERİ TABANI
// SADECE VERİ DEPOSU - HTML veya Fonksiyon İçermez

const universiteVerileri = [
    // --- 1. FAZ: DOĞRULANMIŞ LOKOMOTİF ÜNİVERSİTELER (2025/2026 GÜNCEL KÜRESEL VERİLER) ---
    { 
        id: 1, 
        isim: "Orta Doğu Teknik Üniversitesi (ODTÜ)", 
        universiteLink: "universiteler/odtu.html", 
        bolum: "Mühendislik, Temel Bilimler", 
        kadro: "%95 Tam Zamanlı", 
        urap: "431", 
        qs: "285", 
        the: "351-400" 
    },
    { 
        id: 2, 
        isim: "İstanbul Teknik Üniversitesi (İTÜ)", 
        universiteLink: "universiteler/itu.html", 
        bolum: "Mühendislik & Mimarlık", 
        kadro: "%92 Tam Zamanlı", 
        urap: "492", 
        qs: "326", 
        the: "501-600" 
    },
    { 
        id: 3, 
        isim: "Koç Üniversitesi", 
        universiteLink: "universiteler/koc.html", 
        bolum: "Genel Kapsamlı (Vakıf)", 
        kadro: "%88 Tam Zamanlı", 
        urap: "550", 
        qs: "401", 
        the: "351-400" 
    },
    { 
        id: 4, 
        isim: "Boğaziçi Üniversitesi", 
        universiteLink: "universiteler/boun.html", 
        bolum: "Mühendislik & İİBF", 
        kadro: "%90 Tam Zamanlı", 
        urap: "640", 
        qs: "418", 
        the: "501-600" 
    },
    { 
        id: 5, 
        isim: "Bilkent Üniversitesi", 
        universiteLink: "universiteler/bilkent.html", 
        bolum: "Mühendislik & İİBF (Vakıf)", 
        kadro: "%92 Tam Zamanlı", 
        urap: "700", 
        qs: "477", 
        the: "501-600" 
    },
    { 
        id: 6, 
        isim: "Hacettepe Üniversitesi", 
        universiteLink: "universiteler/hacettepe.html", 
        bolum: "Tıp & Sağlık Bilimleri", 
        kadro: "%98 Tam Zamanlı", 
        urap: "374", 
        qs: "641-650", 
        the: "501-600" 
    },
    { 
        id: 7, 
        isim: "Sabancı Üniversitesi", 
        universiteLink: "universiteler/sabanci.html", 
        bolum: "Mühendislik & Yönetim (Vakıf)", 
        kadro: "%85 Tam Zamanlı", 
        urap: "800", 
        qs: "516", 
        the: "501-600" 
    },
    { 
        id: 8, 
        isim: "Ankara Üniversitesi", 
        universiteLink: "universiteler/ankara.html", 
        bolum: "Tıp, Hukuk & Siyasal", 
        kadro: "%97 Tam Zamanlı", 
        urap: "622", 
        qs: "801-850", 
        the: "801-1000" 
    },
    { 
        id: 9, 
        isim: "İstanbul Üniversitesi", 
        universiteLink: "universiteler/istanbul.html", 
        bolum: "Hukuk, Tıp & Edebiyat", 
        kadro: "%96 Tam Zamanlı", 
        urap: "614", 
        qs: "711-720", 
        the: "801-1000" 
    },
    { 
        id: 10, 
        isim: "Gazi Üniversitesi", 
        universiteLink: "universiteler/gazi.html", 
        bolum: "Eğitim, Tıp & Mühendislik", 
        kadro: "%95 Tam Zamanlı", 
        urap: "726", 
        qs: "851-900", 
        the: "1001-1200" 
    },
    { 
        id: 11, 
        isim: "Yıldız Teknik Üniversitesi", 
        universiteLink: "universiteler/ytu.html", 
        bolum: "Mühendislik & Mimarlık", 
        kadro: "%90 Tam Zamanlı", 
        urap: "860", 
        qs: "741-750", 
        the: "1001-1200" 
    },
    { 
        id: 12, 
        isim: "Ege Üniversitesi", 
        universiteLink: "universiteler/ege.html", 
        bolum: "Tıp & Fen Bilimleri", 
        kadro: "%94 Tam Zamanlı", 
        urap: "780", 
        qs: "1001-1200", 
        the: "1001-1200" 
    },
    { 
        id: 13, 
        isim: "Marmara Üniversitesi", 
        universiteLink: "universiteler/marmara.html", 
        bolum: "İlahiyat, İİBF & Hukuk", 
        kadro: "%93 Tam Zamanlı", 
        urap: "900", 
        qs: "1001-1200", 
        the: "1201-1500" 
    },
    { 
        id: 14, 
        isim: "Dokuz Eylül Üniversitesi", 
        universiteLink: "universiteler/deu.html", 
        bolum: "Tıp, Mühendislik & İİBF", 
        kadro: "%94 Tam Zamanlı", 
        urap: "950", 
        qs: "1201-1400", 
        the: "1201-1500" 
    },
    { 
        id: 15, 
        isim: "Erciyes Üniversitesi", 
        universiteLink: "universiteler/erciyes.html", 
        bolum: "Tıp & Mühendislik", 
        kadro: "%92 Tam Zamanlı", 
        urap: "1015", 
        qs: "1201-1400", 
        the: "1201-1500" 
    },
   // --- 2. FAZ: A VE B HARFİ İLE BAŞLAYAN ÜNİVERSİTELER (ALFABETİK) ---
    { id: 16, isim: "Abdullah Gül Üniversitesi (Kayseri)", universiteLink: "universiteler/agu.html", bolum: "Mühendislik & Yaşam Bilimleri", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "601-800" },
    { id: 17, isim: "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi", universiteLink: "universiteler/atu.html", bolum: "Mühendislik & Teknoloji", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 18, isim: "Adıyaman Üniversitesi", universiteLink: "universiteler/adiyaman.html", bolum: "Genel Kapsamlı", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 19, isim: "Afyon Kocatepe Üniversitesi", universiteLink: "universiteler/aku.html", bolum: "Veterinerlik & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 20, isim: "Afyonkarahisar Sağlık Bilimleri Üniversitesi", universiteLink: "universiteler/afsu.html", bolum: "Sağlık Bilimleri", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 21, isim: "Ağrı İbrahim Çeçen Üniversitesi", universiteLink: "universiteler/agri.html", bolum: "Eğitim & Fen-Edebiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 22, isim: "Akdeniz Üniversitesi (Antalya)", universiteLink: "universiteler/akdeniz.html", bolum: "Tıp & Turizm", kadro: "%85 Tam Zamanlı", urap: "1200", qs: "1201-1400", the: "1501+" },
    { id: 23, isim: "Aksaray Üniversitesi", universiteLink: "universiteler/aksaray.html", bolum: "Genel Kapsamlı", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 24, isim: "Alanya Alaaddin Keykubat Üniversitesi", universiteLink: "universiteler/alanya.html", bolum: "Turizm & İşletme", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 25, isim: "Amasya Üniversitesi", universiteLink: "universiteler/amasya.html", bolum: "Eğitim & Sağlık", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 26, isim: "Anadolu Üniversitesi (Eskişehir)", universiteLink: "universiteler/anadolu.html", bolum: "İletişim, Havacılık & AÖF", kadro: "%80 Tam Zamanlı", urap: "1600", qs: "1201-1400", the: "1201-1500" },
    { id: 27, isim: "Ankara Bilim Üniversitesi", universiteLink: "universiteler/ankarabilim.html", bolum: "Bilgi Yok", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 28, isim: "Ankara Hacı Bayram Veli Üniversitesi", universiteLink: "universiteler/ahbv.html", bolum: "Hukuk & İİBF", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 29, isim: "Ankara Medipol Üniversitesi", universiteLink: "universiteler/ankaramedipol.html", bolum: "Sağlık & Tıp (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 30, isim: "Ankara Müzik ve Güzel Sanatlar Üniversitesi", universiteLink: "universiteler/amgsu.html", bolum: "Sanat & Tasarım", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 31, isim: "Ankara Sosyal Bilimler Üniversitesi", universiteLink: "universiteler/asbu.html", bolum: "Sosyal Bilimler & İlahiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 32, isim: "Ankara Yıldırım Beyazıt Üniversitesi", universiteLink: "universiteler/aybu.html", bolum: "Tıp & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 33, isim: "Antalya Bilim Üniversitesi", universiteLink: "universiteler/antalyabilim.html", bolum: "Mühendislik & Turizm (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 34, isim: "Ardahan Üniversitesi", universiteLink: "universiteler/ardahan.html", bolum: "İnsani Bilimler", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 35, isim: "Artvin Çoruh Üniversitesi", universiteLink: "universiteler/artvin.html", bolum: "Orman & Fen-Edebiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 36, isim: "Atatürk Üniversitesi (Erzurum)", universiteLink: "universiteler/ataturk.html", bolum: "Genel Kapsamlı (Tıp/Ziraat)", kadro: "%90 Tam Zamanlı", urap: "1350", qs: "Listelenmiyor", the: "1501+" },
    { id: 37, isim: "Atılım Üniversitesi (Ankara)", universiteLink: "universiteler/atilim.html", bolum: "Mühendislik & Hukuk (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 38, isim: "Avrasya Üniversitesi (Trabzon)", universiteLink: "universiteler/avrasya.html", bolum: "Genel Kapsamlı (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 39, isim: "Aydın Adnan Menderes Üniversitesi", universiteLink: "universiteler/adu.html", bolum: "Tıp & Veterinerlik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 40, isim: "Balıkesir Üniversitesi", universiteLink: "universiteler/balikesir.html", bolum: "Eğitim & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 41, isim: "Bandırma Onyedi Eylül Üniversitesi", universiteLink: "universiteler/bandirma.html", bolum: "Denizcilik & İİBF", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 42, isim: "Bartın Üniversitesi", universiteLink: "universiteler/bartin.html", bolum: "Orman & Spor Bilimleri", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 43, isim: "Batman Üniversitesi", universiteLink: "universiteler/batman.html", bolum: "Mühendislik & İslami İlimler", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 44, isim: "Bayburt Üniversitesi", universiteLink: "universiteler/bayburt.html", bolum: "Eğitim & İlahiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 45, isim: "Beykent Üniversitesi (İstanbul)", universiteLink: "universiteler/beykent.html", bolum: "İletişim & Mühendislik (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 46, isim: "Beykoz Üniversitesi (İstanbul)", universiteLink: "universiteler/beykoz.html", bolum: "Lojistik & Sanat (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 47, isim: "Bilecik Şeyh Edebali Üniversitesi", universiteLink: "universiteler/bilecik.html", bolum: "Mühendislik & İİBF", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 48, isim: "Bingöl Üniversitesi", universiteLink: "universiteler/bingol.html", bolum: "Ziraat & Veterinerlik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 49, isim: "Biruni Üniversitesi (İstanbul)", universiteLink: "universiteler/biruni.html", bolum: "Sağlık Bilimleri & Tıp (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 50, isim: "Bitlis Eren Üniversitesi", universiteLink: "universiteler/bitlis.html", bolum: "Fen-Edebiyat & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 51, isim: "Bolu Abant İzzet Baysal Üniversitesi", universiteLink: "universiteler/ibu.html", bolum: "Tıp & Eğitim", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 52, isim: "Burdur Mehmet Akif Ersoy Üniversitesi", universiteLink: "universiteler/maku.html", bolum: "Veterinerlik & Eğitim", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 53, isim: "Bursa Teknik Üniversitesi", universiteLink: "universiteler/btu.html", bolum: "Mühendislik & Doğa Bilimleri", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 54, isim: "Bursa Uludağ Üniversitesi", universiteLink: "universiteler/uludag.html", bolum: "Tıp, Otomotiv & İktisat", kadro: "%86 Tam Zamanlı", urap: "1450", qs: "Listelenmiyor", the: "1501+" },// --- 3. FAZ: C'DEN K'YE KADAR OLAN ÜNİVERSİTELER (ALFABETİK) ---
    { id: 55, isim: "Çağ Üniversitesi (Mersin)", universiteLink: "universiteler/cag.html", bolum: "Hukuk & İİBF (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 56, isim: "Çanakkale Onsekiz Mart Üniversitesi", universiteLink: "universiteler/comu.html", bolum: "Arkeoloji, Tarih & Ziraat", kadro: "%84 Tam Zamanlı", urap: "1652", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 57, isim: "Çankırı Karatekin Üniversitesi", universiteLink: "universiteler/karatekin.html", bolum: "Orman & Fen-Edebiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 58, isim: "Çukurova Üniversitesi (Adana)", universiteLink: "universiteler/cukurova.html", bolum: "Tıp & Ziraat", kadro: "%90 Tam Zamanlı", urap: "1150", qs: "1201-1400", the: "1201-1500" },
    { id: 59, isim: "Dicle Üniversitesi (Diyarbakır)", universiteLink: "universiteler/dicle.html", bolum: "Tıp & Hukuk", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 60, isim: "Doğuş Üniversitesi (İstanbul)", universiteLink: "universiteler/dogus.html", bolum: "Mühendislik & Sanat (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 61, isim: "Dokuz Eylül Üniversitesi (İzmir)", universiteLink: "universiteler/deu.html", bolum: "Tıp, Mühendislik & İİBF", kadro: "%94 Tam Zamanlı", urap: "950", qs: "1201-1400", the: "1201-1500" },
    { id: 62, isim: "Düzce Üniversitesi", universiteLink: "universiteler/duzce.html", bolum: "Orman & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 63, isim: "Erzincan Binali Yıldırım Üniversitesi", universiteLink: "universiteler/erzincan.html", bolum: "Hukuk & Eğitim", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 64, isim: "Erzurum Teknik Üniversitesi", universiteLink: "universiteler/erzurumteknik.html", bolum: "Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 65, isim: "Eskişehir Osmangazi Üniversitesi", universiteLink: "universiteler/ogu.html", bolum: "Tıp & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 66, isim: "Eskişehir Teknik Üniversitesi", universiteLink: "universiteler/estu.html", bolum: "Havacılık & Uzay", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 67, isim: "Fatih Sultan Mehmet Vakıf Üniversitesi", universiteLink: "universiteler/fsm.html", bolum: "Mimarlık & İslami İlimler", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 68, isim: "Fenerbahçe Üniversitesi (İstanbul)", universiteLink: "universiteler/fbu.html", bolum: "Spor Bilimleri & İletişim (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 69, isim: "Fırat Üniversitesi (Elazığ)", universiteLink: "universiteler/firat.html", bolum: "Mühendislik & Veterinerlik", kadro: "%88 Tam Zamanlı", urap: "1050", qs: "1201-1400", the: "1201-1500" },
    { id: 70, isim: "Galatasaray Üniversitesi (İstanbul)", universiteLink: "universiteler/gsu.html", bolum: "Hukuk, İktisat & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 71, isim: "Gaziantep İslam Bilim ve Teknoloji Üniversitesi", universiteLink: "universiteler/gibtu.html", bolum: "İslami İlimler & Teknoloji", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 72, isim: "Gaziantep Üniversitesi", universiteLink: "universiteler/gantep.html", bolum: "Tıp & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 73, isim: "Gebze Teknik Üniversitesi (Kocaeli)", universiteLink: "universiteler/gtu.html", bolum: "İleri Mühendislik & Temel Bil.", kadro: "%82 Tam Zamanlı", urap: "1500", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 74, isim: "Giresun Üniversitesi", universiteLink: "universiteler/giresun.html", bolum: "Eğitim & Fen-Edebiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 75, isim: "Gümüşhane Üniversitesi", universiteLink: "universiteler/gumushane.html", bolum: "İletişim & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 76, isim: "Hakkari Üniversitesi", universiteLink: "universiteler/hakkari.html", bolum: "Eğitim & İlahiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 77, isim: "Haliç Üniversitesi (İstanbul)", universiteLink: "universiteler/halic.html", bolum: "Sağlık & Mimarlık (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 78, isim: "Harran Üniversitesi (Şanlıurfa)", universiteLink: "universiteler/harran.html", bolum: "Ziraat & İlahiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 79, isim: "Hasan Kalyoncu Üniversitesi (Gaziantep)", universiteLink: "universiteler/hku.html", bolum: "Eğitim & İletişim (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 80, isim: "Hatay Mustafa Kemal Üniversitesi", universiteLink: "universiteler/mku.html", bolum: "Tıp & Ziraat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 81, isim: "Hitit Üniversitesi (Çorum)", universiteLink: "universiteler/hitit.html", bolum: "Mühendislik & İlahiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 82, isim: "Iğdır Üniversitesi", universiteLink: "universiteler/igdir.html", bolum: "Ziraat & İlahiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 83, isim: "Isparta Uygulamalı Bilimler Üniversitesi", universiteLink: "universiteler/isubu.html", bolum: "Orman & Ziraat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 84, isim: "Işık Üniversitesi (İstanbul)", universiteLink: "universiteler/isik.html", bolum: "Mühendislik & Sanat (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 85, isim: "İbn Haldun Üniversitesi (İstanbul)", universiteLink: "universiteler/ihu.html", bolum: "Sosyal Bilimler (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 86, isim: "İnönü Üniversitesi (Malatya)", universiteLink: "universiteler/inonu.html", bolum: "Tıp & Eğitim", kadro: "%90 Tam Zamanlı", urap: "1350", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 87, isim: "İskenderun Teknik Üniversitesi (İSTE)", universiteLink: "universiteler/iste.html", bolum: "Mühendislik & Denizcilik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 88, isim: "İstanbul Arel Üniversitesi", universiteLink: "universiteler/arel.html", bolum: "İletişim & İİBF (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 89, isim: "İstanbul Atlas Üniversitesi", universiteLink: "universiteler/atlas.html", bolum: "Diş Hekimliği & Sağlık (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 90, isim: "İstanbul Aydın Üniversitesi", universiteLink: "universiteler/aydin.html", bolum: "Genel Kapsamlı (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 91, isim: "İstanbul Bilgi Üniversitesi", universiteLink: "universiteler/bilgi.html", bolum: "İletişim & Hukuk (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 92, isim: "İstanbul Cerrahpaşa Üniversitesi", universiteLink: "universiteler/cerrahpasa.html", bolum: "Tıp & Veterinerlik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 93, isim: "İstanbul Galata Üniversitesi", universiteLink: "universiteler/galata.html", bolum: "Diş Hekimliği & Sanat (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 94, isim: "İstanbul Gelişim Üniversitesi", universiteLink: "universiteler/gelisim.html", bolum: "Mühendislik & İİBF (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 95, isim: "İstanbul Kent Üniversitesi", universiteLink: "universiteler/kent.html", bolum: "Sağlık Bilimleri (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 96, isim: "İstanbul Kültür Üniversitesi", universiteLink: "universiteler/kultur.html", bolum: "Mimarlık & Hukuk (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 97, isim: "İstanbul Medeniyet Üniversitesi", universiteLink: "universiteler/medeniyet.html", bolum: "Tıp & Hukuk", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 98, isim: "İstanbul Okan Üniversitesi", universiteLink: "universiteler/okan.html", bolum: "Tıp & Mühendislik (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 99, isim: "İstanbul Rumeli Üniversitesi", universiteLink: "universiteler/rumeli.html", bolum: "Sağlık & Mühendislik (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 100, isim: "İstanbul Sabahattin Zaim Üniversitesi", universiteLink: "universiteler/izu.html", bolum: "İslami İlimler & Eğitim (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 101, isim: "İstanbul Sağlık ve Teknoloji Üniversitesi", universiteLink: "universiteler/istun.html", bolum: "Eczacılık & Tıp (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 102, isim: "İstanbul Ticaret Üniversitesi", universiteLink: "universiteler/ticaret.html", bolum: "İşletme & Hukuk (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 103, isim: "İstinye Üniversitesi (İstanbul)", universiteLink: "universiteler/istinye.html", bolum: "Tıp & Yapay Zeka (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 104, isim: "İzmir Bakırçay Üniversitesi", universiteLink: "universiteler/bakircay.html", bolum: "Hukuk & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 105, isim: "İzmir Demokrasi Üniversitesi", universiteLink: "universiteler/demokrasi.html", bolum: "Tıp & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 106, isim: "İzmir Ekonomi Üniversitesi", universiteLink: "universiteler/izmirekonomi.html", bolum: "İktisat & Lojistik (Vakıf)", kadro: "%72 Tam Zamanlı", urap: "2350", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 107, isim: "İzmir Katip Çelebi Üniversitesi", universiteLink: "universiteler/ikcu.html", bolum: "Tıp & Diş Hekimliği", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 108, isim: "İzmir Yüksek Teknoloji Enstitüsü (İYTE)", universiteLink: "universiteler/iyte.html", bolum: "Mühendislik & Doğa Bilimleri", kadro: "%95 Tam Zamanlı", urap: "1200", qs: "Listelenmiyor", the: "1501+" },
    { id: 109, isim: "Kadir Has Üniversitesi (İstanbul)", universiteLink: "universiteler/khas.html", bolum: "İletişim & Mühendislik (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 110, isim: "Kafkas Üniversitesi (Kars)", universiteLink: "universiteler/kafkas.html", bolum: "Veterinerlik & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 111, isim: "Kahramanmaraş İstiklal Üniversitesi", universiteLink: "universiteler/istiklal.html", bolum: "Mühendislik & Mimarlık", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 112, isim: "Kahramanmaraş Sütçü İmam Üniversitesi", universiteLink: "universiteler/ksu.html", bolum: "Orman & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 113, isim: "Kapadokya Üniversitesi (Nevşehir)", universiteLink: "universiteler/kapadokya.html", bolum: "Havacılık & Turizm (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 114, isim: "Karabük Üniversitesi", universiteLink: "universiteler/karabuk.html", bolum: "Mühendislik & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 115, isim: "Karadeniz Teknik Üniversitesi (Trabzon)", universiteLink: "universiteler/ktu.html", bolum: "Mühendislik & Tıp", kadro: "%92 Tam Zamanlı", urap: "1150", qs: "Listelenmiyor", the: "1501+" },
    { id: 116, isim: "Karamanoğlu Mehmetbey Üniversitesi (Karaman)", universiteLink: "universiteler/kmu.html", bolum: "Edebiyat & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 117, isim: "Karatay Üniversitesi (Konya)", universiteLink: "universiteler/karatay.html", bolum: "Hukuk & Tıp (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 118, isim: "Kastamonu Üniversitesi", universiteLink: "universiteler/kastamonu.html", bolum: "Orman & Eğitim", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 119, isim: "Kırıkkale Üniversitesi", universiteLink: "universiteler/kirikkale.html", bolum: "Hukuk & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 120, isim: "Kırklareli Üniversitesi", universiteLink: "universiteler/kirklareli.html", bolum: "Turizm & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 121, isim: "Kırşehir Ahi Evran Üniversitesi", universiteLink: "universiteler/ahievran.html", bolum: "Eğitim & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 122, isim: "Kilis 7 Aralık Üniversitesi", universiteLink: "universiteler/kilis.html", bolum: "İlahiyat & Eğitim", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 123, isim: "Kocaeli Sağlık ve Teknoloji Üniversitesi", universiteLink: "universiteler/kostu.html", bolum: "Sağlık Bilimleri (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 124, isim: "Kocaeli Üniversitesi", universiteLink: "universiteler/kocaeli.html", bolum: "Mühendislik & Tıp", kadro: "%88 Tam Zamanlı", urap: "1250", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 125, isim: "Konya Teknik Üniversitesi", universiteLink: "universiteler/ktun.html", bolum: "Mühendislik & Mimarlık", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 126, isim: "Kütahya Dumlupınar Üniversitesi", universiteLink: "universiteler/dpu.html", bolum: "İİBF & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 127, isim: "Kütahya Sağlık Bilimleri Üniversitesi", universiteLink: "universiteler/ksbu.html", bolum: "Sağlık & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },// --- 4. FAZ: L'DEN Z'YE KADAR OLAN ÜNİVERSİTELER (ALFABETİK) ---
    { id: 128, isim: "Lokman Hekim Üniversitesi (Ankara)", universiteLink: "universiteler/lokmanhekim.html", bolum: "Tıp & Sağlık (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 129, isim: "Malatya Turgut Özal Üniversitesi", universiteLink: "universiteler/mto.html", bolum: "Ziraat & İşletme", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 130, isim: "Maltepe Üniversitesi (İstanbul)", universiteLink: "universiteler/maltepe.html", bolum: "İletişim & Hukuk (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 131, isim: "Manisa Celal Bayar Üniversitesi", universiteLink: "universiteler/cbu.html", bolum: "Tıp & Mühendislik", kadro: "%88 Tam Zamanlı", urap: "1400", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 132, isim: "Mardin Artuklu Üniversitesi", universiteLink: "universiteler/artuklu.html", bolum: "Mimarlık & Edebiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 133, isim: "MEF Üniversitesi (İstanbul)", universiteLink: "universiteler/mef.html", bolum: "Eğitim & Mühendislik (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 134, isim: "Mersin Üniversitesi", universiteLink: "universiteler/mersin.html", bolum: "Tıp & Eğitim", kadro: "%86 Tam Zamanlı", urap: "1550", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 135, isim: "Mimar Sinan Güzel Sanatlar Üniversitesi (İstanbul)", universiteLink: "universiteler/msgsu.html", bolum: "Mimarlık & Sanat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 136, isim: "Mudanya Üniversitesi (Bursa)", universiteLink: "universiteler/mudanya.html", bolum: "Sanat & Sosyal (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 137, isim: "Muğla Sıtkı Koçman Üniversitesi", universiteLink: "universiteler/mu.html", bolum: "Turizm & Fen", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 138, isim: "Munzur Üniversitesi (Tunceli)", universiteLink: "universiteler/munzur.html", bolum: "Mühendislik & Edebiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 139, isim: "Muş Alparslan Üniversitesi", universiteLink: "universiteler/mus.html", bolum: "İslami İlimler & Eğitim", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 140, isim: "Necmettin Erbakan Üniversitesi (Konya)", universiteLink: "universiteler/neu.html", bolum: "Eğitim & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 141, isim: "Nevşehir Hacı Bektaş Veli Üniversitesi", universiteLink: "universiteler/nevsehir.html", bolum: "Turizm & Fen-Edebiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 142, isim: "Niğde Ömer Halisdemir Üniversitesi", universiteLink: "universiteler/ohu.html", bolum: "Tarım & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 143, isim: "Nişantaşı Üniversitesi (İstanbul)", universiteLink: "universiteler/nisantasi.html", bolum: "İletişim & Sanat (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 144, isim: "Nuh Naci Yazgan Üniversitesi (Kayseri)", universiteLink: "universiteler/nny.html", bolum: "Mühendislik & İİBF (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 145, isim: "Ondokuz Mayıs Üniversitesi (Samsun)", universiteLink: "universiteler/omu.html", bolum: "Tıp, Eğitim & Ziraat", kadro: "%86 Tam Zamanlı", urap: "1400", qs: "1401+", the: "1501+" },
    { id: 146, isim: "Ordu Üniversitesi", universiteLink: "universiteler/ordu.html", bolum: "Ziraat & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 147, isim: "Osmaniye Korkut Ata Üniversitesi", universiteLink: "universiteler/osmaniye.html", bolum: "Mühendislik & İlahiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 148, isim: "Ostim Teknik Üniversitesi (Ankara)", universiteLink: "universiteler/ostim.html", bolum: "Mühendislik & Sanayi (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 149, isim: "Pamukkale Üniversitesi (Denizli)", universiteLink: "universiteler/pau.html", bolum: "Tıp & Mühendislik", kadro: "%88 Tam Zamanlı", urap: "1450", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 150, isim: "Piri Reis Üniversitesi (İstanbul)", universiteLink: "universiteler/pirireis.html", bolum: "Denizcilik (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 151, isim: "Recep Tayyip Erdoğan Üniversitesi (Rize)", universiteLink: "universiteler/erdogan.html", bolum: "Tıp & Su Ürünleri", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 152, isim: "Sağlık Bilimleri Üniversitesi (İstanbul)", universiteLink: "universiteler/sbu.html", bolum: "Tıp & Sağlık Bilimleri", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 153, isim: "Sakarya Uygulamalı Bilimler Üniversitesi", universiteLink: "universiteler/subu.html", bolum: "Teknoloji & Tarım", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 154, isim: "Sakarya Üniversitesi", universiteLink: "universiteler/sakarya.html", bolum: "Mühendislik & İİBF", kadro: "%90 Tam Zamanlı", urap: "1350", qs: "1201-1400", the: "1501+" },
    { id: 155, isim: "Samsun Üniversitesi", universiteLink: "universiteler/samsun.html", bolum: "Havacılık & Uzay", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 156, isim: "Sanko Üniversitesi (Gaziantep)", universiteLink: "universiteler/sanko.html", bolum: "Tıp & Sağlık (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 157, isim: "Selçuk Üniversitesi (Konya)", universiteLink: "universiteler/selcuk.html", bolum: "Hukuk, Tıp & Ziraat", kadro: "%92 Tam Zamanlı", urap: "1250", qs: "1201-1400", the: "1501+" },
    { id: 158, isim: "Siirt Üniversitesi", universiteLink: "universiteler/siirt.html", bolum: "Ziraat & İlahiyat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 159, isim: "Sinop Üniversitesi", universiteLink: "universiteler/sinop.html", bolum: "Su Ürünleri & Eğitim", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 160, isim: "Sivas Bilim ve Teknoloji Üniversitesi", universiteLink: "universiteler/sbtu.html", bolum: "Mühendislik & Tarım", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 161, isim: "Sivas Cumhuriyet Üniversitesi", universiteLink: "universiteler/cumhuriyet.html", bolum: "Tıp & Diş Hekimliği", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 162, isim: "Süleyman Demirel Üniversitesi (Isparta)", universiteLink: "universiteler/sdu.html", bolum: "Tıp & Diş Hekimliği", kadro: "%88 Tam Zamanlı", urap: "1350", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 163, isim: "Şırnak Üniversitesi", universiteLink: "universiteler/sirnak.html", bolum: "İlahiyat & Ziraat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 164, isim: "Tarsus Üniversitesi", universiteLink: "universiteler/tarsus.html", bolum: "Havacılık & Uzay", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 165, isim: "TED Üniversitesi (Ankara)", universiteLink: "universiteler/tedu.html", bolum: "Eğitim & Mühendislik (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 166, isim: "Tekirdağ Namık Kemal Üniversitesi", universiteLink: "universiteler/nku.html", bolum: "Tıp & Ziraat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 167, isim: "TOBB Ekonomi ve Teknoloji Üni. (Ankara)", universiteLink: "universiteler/tobb.html", bolum: "Mühendislik & Hukuk (Vakıf)", kadro: "%90 Tam Zamanlı", urap: "1300", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 168, isim: "Tokat Gaziosmanpaşa Üniversitesi", universiteLink: "universiteler/gop.html", bolum: "Ziraat & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 169, isim: "Toros Üniversitesi (Mersin)", universiteLink: "universiteler/toros.html", bolum: "Sağlık & Mühendislik (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 170, isim: "Trabzon Üniversitesi", universiteLink: "universiteler/trabzon.html", bolum: "Hukuk & İletişim", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 171, isim: "Trakya Üniversitesi (Edirne)", universiteLink: "universiteler/trakya.html", bolum: "Tıp & Balkan Çalışmaları", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 172, isim: "Türk-Alman Üniversitesi (İstanbul)", universiteLink: "universiteler/tau.html", bolum: "Mühendislik & Hukuk", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 173, isim: "Türk-Japon Bilim ve Teknoloji Üni. (İstanbul)", universiteLink: "universiteler/tju.html", bolum: "Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 174, isim: "Ufuk Üniversitesi (Ankara)", universiteLink: "universiteler/ufuk.html", bolum: "Tıp & Hukuk (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 175, isim: "Uşak Üniversitesi", universiteLink: "universiteler/usak.html", bolum: "Tekstil & Diş Hekimliği", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 176, isim: "Üsküdar Üniversitesi (İstanbul)", universiteLink: "universiteler/uskudar.html", bolum: "Psikoloji & Sağlık (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 177, isim: "Van Yüzüncü Yıl Üniversitesi", universiteLink: "universiteler/yyu.html", bolum: "Veterinerlik & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 178, isim: "Yalova Üniversitesi", universiteLink: "universiteler/yalova.html", bolum: "Hukuk & Mühendislik", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 179, isim: "Yaşar Üniversitesi (İzmir)", universiteLink: "universiteler/yasar.html", bolum: "Sanat, Tasarım & Hukuk (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 180, isim: "Yeditepe Üniversitesi (İstanbul)", universiteLink: "universiteler/yeditepe.html", bolum: "Diş Hekimliği & Tıp (Vakıf)", kadro: "%85 Tam Zamanlı", urap: "1850", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 181, isim: "Yozgat Bozok Üniversitesi", universiteLink: "universiteler/bozok.html", bolum: "Tıp & Ziraat", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 182, isim: "Yüksek İhtisas Üniversitesi (Ankara)", universiteLink: "universiteler/yiu.html", bolum: "Tıp & Sağlık Bilimleri (Vakıf)", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" },
    { id: 183, isim: "Zonguldak Bülent Ecevit Üniversitesi", universiteLink: "universiteler/beun.html", bolum: "Mühendislik & Tıp", kadro: "Bilgi Yok", urap: "Listelenmiyor", qs: "Listelenmiyor", the: "Listelenmiyor" }
// DİZİ BURADA TAMAMEN KAPANDI - BAŞKA VERİ EKLENMEYECEK
];
